services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_TICK_TIME=2000
      - ZOO_INIT_LIMIT=10
      - ZOO_SYNC_LIMIT=5
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    healthcheck:
      test: [ "CMD", "zkServer.sh", "status" ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    stop_grace_period: 1m

  kafka:
    image: bitnami/kafka:3.4.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      # Increase these timeouts significantly
      - KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS=120000
      - KAFKA_CFG_ZOOKEEPER_SESSION_TIMEOUT_MS=120000
      # Add these for better restart behavior
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_CFG_AUTO_LEADER_REBALANCE_ENABLE=true
    volumes:
      - kafka_data:/bitnami/kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --list --bootstrap-server localhost:9092 || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 120s
    restart: on-failure
    stop_grace_period: 3m

  kafka-consumer-app:
    build: .
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CONSUMER_GROUP=kpipe-group
      - KAFKA_TOPIC=json-topic
      - APP_NAME=kafka-consumer-app
    depends_on:
      - kafka
    restart: unless-stopped

  kafka-init:
    image: bitnami/kafka:3.4.1
    depends_on:
      - kafka
    command: >
      sh -c "
        echo 'Waiting for Kafka to be ready...' &&
        sleep 30 &&
        kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --partitions 3 --replication-factor 1 --topic json-topic &&
        echo 'Topic created successfully'
      "
    restart: on-failure

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local