name: Build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "graalvm"
          java-version: "24"
          cache: "gradle"

      - name: Test with Gradle
        run: ./gradlew clean spotlessApply build

      - name: Jacoco
        run: ./gradlew :lib:jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            slug: eschizoid/kpipe
            files: ./lib/build/reports/jacoco/test/jacocoTestReport.xml
