name: Build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "graalvm"
          java-version: "25"
          cache: "gradle"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Test with Gradle
        run: |
          ./gradlew clean
          ./gradlew spotlessApply
          ./gradlew build test --stacktrace --no-daemon --max-workers=2

      - name: Jacoco
        run: ./gradlew :lib:kpipe-consumer:jacocoTestReport :lib:kpipe-producer:jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: eschizoid/kpipe
          files: |
            ./lib/kpipe-consumer/build/reports/jacoco/test/jacocoTestReport.xml
            ./lib/kpipe-producer/build/reports/jacoco/test/jacocoTestReport.xml
