name: Build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "23"
          cache: "gradle"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Test with Gradle
        run: |
          ./gradlew clean
          ./gradlew spotlessApply
          ./gradlew build -Dorg.gradle.jvmargs="-Xmx2g -Xms2g -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError" --stacktrace --scan --info

      - name: Jacoco
        run: ./gradlew :lib:jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: eschizoid/kpipe
          files: ./lib/build/reports/jacoco/test/jacocoTestReport.xml
