name: Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release Type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "graalvm"
          java-version: "24"
          cache: "gradle"

      - name: Set Git Identity
        run: |
          git config --global user.email "mariano.gonzalez.mx@gmail.com"
          git config --global user.name "Mariano Gonzalez"

      - name: Setup GPG
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Update Version and Create Tag
        id: version
        run: |
          # Create release with specified increment type
          ./gradlew release -Prelease.incrementer=${{ inputs.releaseType }} -Prelease.disableChecks -x test

          # Get the version number more explicitly
          RAW_VERSION=$(./gradlew currentVersion -q -Prelease.quiet)
          echo "Raw version: $RAW_VERSION"

          # Use the actual tag name that was created (with 'v' prefix)
          TAG_VERSION="v$RAW_VERSION"

          echo "version=$RAW_VERSION" >> $GITHUB_OUTPUT
          echo "tagName=$TAG_VERSION" >> $GITHUB_OUTPUT

          echo "Setting version to $RAW_VERSION"
          
          echo "org.jreleaser.version=$RAW_VERSION" >> gradle.properties

      - name: Build project
        run: |
          ./gradlew clean :lib:build
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tagName }}
          name: Release ${{ steps.version.outputs.version }}
          generate_release_notes: true

      - name: Publish to Maven Central
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          JRELEASER_MAVENCENTRAL_SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          JRELEASER_MAVENCENTRAL_SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          JRELEASER_PROJECT_VERSION: ${{ steps.version.outputs.version }}
          JRELEASER_GITHUB_OVERWRITE: "true"
          JRELEASER_GITHUB_UPDATE: "true"
        run: |
          # Let JReleaser handle both the publishing and releasing
          ./gradlew :lib:jreleaserFullRelease --stacktrace -Pversion=${{ steps.version.outputs.version }}
