name: Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release Type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "graalvm"
          java-version: "23"
          cache: "gradle"

      - name: Set Git Identity
        run: |
          git config --global user.email "marian.gonzalez.mx@gmail.com"
          git config --global user.name "Mariano Gonzalez"

      - name: Create Release
        id: release
        run: |
          # Create release with specified increment type
          ./gradlew release -Prelease.incrementer=${{ inputs.releaseType }} -Prelease.disableChecks -x test
          
          # Get the new version after release
          NEW_VERSION=$(./gradlew currentVersion -q -Prelease.quiet)
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.release.outputs.version }}
          name: Release ${{ steps.release.outputs.version }}
          generate_release_notes: true
          files: |
            build/libs/kpipe-${{ steps.release.outputs.version }}.jar
