name: Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release Type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "graalvm"
          java-version: "23"
          cache: "gradle"

      - name: Set Git Identity
        run: |
          git config --global user.email "marian.gonzalez.mx@gmail.com"
          git config --global user.name "Mariano Gonzalez"

      - name: Update Version and Create Tag
        id: version
        run: |
          # Create release with specified increment type
          ./gradlew release -Prelease.incrementer=${{ inputs.releaseType }} -Prelease.disableChecks -x test

          # Get the version number
          RAW_VERSION=$(./gradlew currentVersion -q -Prelease.quiet)

          # Use the actual tag name that was created (with 'v' prefix)
          TAG_VERSION="v$RAW_VERSION"

          echo "version=$RAW_VERSION" >> $GITHUB_OUTPUT
          echo "tagName=$TAG_VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tagName }}
          name: Release ${{ steps.version.outputs.version }}
          generate_release_notes: true
          files: |
            build/libs/kpipe-${{ steps.version.outputs.version }}.jar
